# Hologram Generic Verifier Chart Values
# This file contains the default values for the Hologram Generic Verifier Helm chart.
global:
  domain: example.dev.io

name: hologram-generic-verifier-vs
containerPort: 2904
replicas: 1

ingress:
  host: "{{ .Values.name }}.{{ .Values.global.domain }}"
  tlsSecret: public.{{ .Values.name }}.{{ .Values.global.domain }}-cert

service:
  vsAgentAdminBaseUrl: http://verifier-agent:3000
  issuerDid: did:web:issuer.{{ .Values.global.domain }}
  issuerLabel: test-issuer
  issuerImageUrl: https://i.unic-id-issuer.{{ .Values.global.domain }}/avatar.png
  # Use only if you want to use the vs-agent with a credential definition Id
  # If you use both credentialDefinitionId and issuerVsAgentAdminBaseUrl, the issuerVsAgentAdminBaseUrl will be ignored
  credentialDefinitionId: credential-definition-id
  # issuerVsAgentAdminBaseUrl: http://issuer:3000

# If you want to use the vs-agent-chart, you can enable it by setting the following:
# vs-agent-chart.enabled: true
vs-agent-chart:
  enabled: false
  name: verifier-agent
  didcommLabel: test-verifier-agent
  eventsBaseUrl: http://hologram-generic-verifier-vs:2904
  didcommInvitationImageUrl: https://i.unic-id-issuer.demos.dev.2060.io/avatar.png
  ingress:
    host: "{{ .Values.name }}.{{ .Values.global.domain }}" # Host for the vs agent service
    tlsSecret: public.{{ .Values.name }}.{{ .Values.global.domain }}-cert # TLS secret for the vs agent service

  extraEnv: 
    - name: PUBLIC_API_BASE_URL
      value: "https://{{ .Values.name }}.{{ .Values.global.domain }}"
    - name: USE_CORS
      value: "true"

